version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: pycart
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "~/workspace/mariadb/conf:/etc/mysql/conf.d"
      - "~/workspace/mariadb/data:/var/lib/mysql"
  web:
    build: 
      context: .
      args:
        SETTING_FILE: settings.dev.py
    ports:
     - "8080:8080"
